# This is a basic workflow to help you get started with Actions

name: Generate Firmwares

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Fix 402 error
      - name: remove git-lfs
        shell: bash
        run: |
          sudo rm /etc/apt/sources.list.d/github_git-lfs.list 
      - name: setup
        run: |
          export QMK_HOME='~/qmk_firmware
          pip install milc
          python3 -m pip install --user qmk
          qmk setup -y
      - name: list files
        run: |
          ls ~/qmk_firmware

